version: "2.0"

services:
  aeon-ghost-node:
    image: ghcr.io/crushiodarhk/aeon_aegis:latest
    expose:
      - port: 9000
        as: 9000
        to:
          - global: true

profiles:
  compute:
    aeon-ghost-node:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    akash:
      pricing:
        aeon-ghost-node:
          denom: uact
          amount: 1000

deployment:
  aeon-ghost-node:
    akash:
      profile: aeon-ghost-node
      count: 1